# CI/ CD on github page

name: Simple Image Processor
description: Simplest Image Processor

# baseurl = repository name
baseurl: /image_processor

# Render markdown using Kramdown
# and also render html block
markdown: kramdown
kramdown:
  parse_block_html: true

# theme: minima

